name: Auto Assign PRs

on:
  pull_request_target:
    types:
      - opened


  workflow_dispatch:
jobs:
  assignee:
    uses: clouddrove/github-shared-workflows/.github/workflows/auto_assignee.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      assignees: 'clouddrove-ci'
