name: tf-lint
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
jobs:
  tflint:
    uses: clouddrove/test-tfsec/.github/workflows/tflint.yaml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
