name: tfsec
permissions: write-all
on:
  pull_request:
  workflow_dispatch:
jobs:
  tfsec:
    uses: clouddrove/github-shared-workflows/.github/workflows/tfsec.yml@master
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      working_directory: '.'
